// flow-typed signature: 2e54f5e4267818582ea5a6c80c189d46
// flow-typed version: <<STUB>>/postcss-preset-env_v6.5.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-preset-env/index' {
  declare module.exports: $Exports<'postcss-preset-env'>;
}
declare module 'postcss-preset-env/index.js' {
  declare module.exports: $Exports<'postcss-preset-env'>;
}
